home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:pays>/', views.pays, name='pays'),
    path('<str:pays>/<str:prov>/', views.province, name='province'),
    path('<str:pays>/<str:prov>/<str:com>/', views.comte, name='comte'),
]

projetcovid/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
import sqlite3
from home.modeles.importDonneesBasiques import *
from home.modeles.importcsv import DailyQuant
from home.modeles.requetesPourMap import recupPaysDeath
from home.modeles.requetesPourChart import recupDeathDernierMois
from home.modeles.requetesPourViews import recupListePays, recupListeProv, recupListeComte
from home.modeles.requetesPourViews import getCombinedKeyPays, getCombinedKeyProv, getCombinedKeyComte

#pour afficher la page d'index
def index(request):
        conn = sqlite3.connect('covid.db')
        cursor = conn.cursor()
        listePays = recupListePays(cursor)

        #on fait les requetes pour la map
        dicoPaysDeaths, dicoException = recupPaysDeath(cursor)
        listDeath, listDate, listIR = recupDeathDernierMois(cursor)

        listeDonnees = importDonneesBasiquesAvg(cursor)
        context = {'listePays': listePays,
                   'dicoPaysDeaths': dicoPaysDeaths,
                   'dicoException': dicoException,
                   'listeDeath': listDeath,
                   'listeDate': listDate,
                   'listeIR': listIR}
        context.update(listeDonnees)

        conn.close()

        return render(request, 'home/index.html', context)

#pour afficher la page de pays
def pays(request, pays):
        conn = sqlite3.connect('covid.db')
        cursor = conn.cursor()
        listeProv = recupListeProv(cursor, pays)

        #si il n'y a pas de provinces
        if (len(listeProv) == 1 and listeProv[0] == pays) or len(listeProv) == 0:
                combKey = getCombinedKeyPays(cursor, pays)
                listeLatLong, dicoDonnees = importDonneesBasiques(cursor, combKey)
                context = {'com': pays,
                            'prov': pays,
                            'pays': pays,
                            'nbSousCateg':0}
                context.update(listeLatLong)
                context.update(dicoDonnees)
                return render(request, 'home/comte.html', context)

        listeDonnees = importDonneesBasiquesProvinceAvg(cursor, pays)
        context = {'pays': pays,
                   'listeProv': listeProv}
        context.update(listeDonnees)

        conn.close()
        return render(request, 'home/pays.html', context)

#pour afficher la page des provinces
def province(request, pays, prov):
        conn = sqlite3.connect('covid.db')
        cursor = conn.cursor()
        listeCom = recupListeComte(cursor, prov)

        #si il y a pas de comptes
        if (len(listeCom) == 1 and listeCom[0] == prov) or len(listeCom) == 0:
                combKey = getCombinedKeyProv(cursor, pays, prov)
                listeLatLong, dicoDonnees = importDonneesBasiques(cursor, combKey)

                context = {'com': prov,
                           'prov': prov,
                           'pays': pays,
                           'nbSousCateg':1}
                context.update(listeLatLong)
                context.update(dicoDonnees)
                return render(request, 'home/comte.html', context) #page finale

        listeDonnees = importDonneesBasiquesComteAvg(cursor, pays, prov)
        context = {'pays': pays,
                   'prov': prov,
                   'listeCom': listeCom}
        context.update(listeDonnees)

        conn.close()
        return render(request, 'home/province.html', context)

#pour afficher la page de comte
def comte(request, pays, prov, com):
        conn = sqlite3.connect('covid.db')
        cursor = conn.cursor()
        combKey = getCombinedKeyComte(cursor, prov, com)
        listeLatLong, dicoDonnees = importDonneesBasiques(cursor, combKey)
        conn.close()

        context = {'com': com,
                   'prov': prov,
                   'pays': pays,
                   'nbSousCateg':2}
        context.update(listeLatLong)
        context.update(dicoDonnees)
        return render(request, 'home/comte.html', context)

home/templates/home/base.html
<!DOCTYPE html>
{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Projet Covid</title>
    <link type="text/css" rel="stylesheet" href="{% static 'home/css/materialize.min.css' %}" media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="{% static 'home/css/styles.css' %}" media="screen"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="shortcut icon" href="#" />
    {% block styles %}{% endblock %}
</head>
<body>
    <header>
      <nav class="blue-grey">
        <div class="navbar-fixed ">
            <div class="nav-wrapper blue-grey">
                <a href="{% url 'home:index' %}" class="brand-logo  center">
                    <img src="{% static 'home/logo_covid.png' %}" width = 55px height=55px alt="logo">
                    Projet Covid</a>
            </div>
        </div>
      </nav>
    </header>

    <main>
        {% block body %}{% endblock %}
    </main>

    <footer class="page-footer grey darken-1">
        <div class="footer-copyright">
            <div class="container">
                Constans Adelin - Gomez Malaurie
          <a class="grey-text text-lighten-4 right" href="http://cazabetremy.fr/wiki/doku.php?id=projet:lifprojet">lifprojet</a>
        </div>
      </div>
    </footer>
    <script type="text/javascript" src="{% static 'home/js/materialize.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'home/js/map.js' %}"></script>
    <script type="text/javascript" src="{% static 'home/js/chart.js' %}"></script>
    <script type="text/javascript" src="{% static 'home/js/app.js' %}"></script>
    {% block script %} {% endblock %}


</body>
</html>

home/templates/home/comte.html
{% extends 'home/base.html' %}

{% block body %}
    <nav>
        <div class="nav-wrapper blue-grey lighten-1">
            <div class="col s12">
                <a href="{% url 'home:index' %}" class="breadcrumb">Home</a>
                <a href="{% url 'home:pays' pays %}" class="breadcrumb">{{ pays }}</a>
                {% if nbSousCateg > 0 %}
                    <a href="{% url 'home:province' pays prov %}" class="breadcrumb">{{ prov }}</a>
                {% endif %}
                {% if nbSousCateg > 1 %}
                        <a href="#" class="breadcrumb">{{ com }}</a>
                    {% endif %}
                </div>
        </div>
    </nav>

    <h3 id="titre"> {{ com }} </h3>
    <div id="container">
        <div class="card-panel teal lighten-3 white-text " id="latlong">
            <h5> Coordonnées</h5>
            <ul>
                <li>Latitude : {{ Latitude }}</li>
                <li>Longitude : {{ Longitude }}</li>
            </ul>
        </div>


        <div class="card-panel teal lighten-3 white-text" id="stats">
            <h5> Données du {{ Date }}</h5>
            <ul>
                <li>Nombre de déces : {{ Deaths }}</li>
                <li>Nombre de cas confirmés : {{ Confirmed }}</li>
                <li>Nombre de guérris : {{ Recovered }}</li>
                <li>Nombre de cas actifs : {{ Active }}</li>
                <li>Taux d'incidence : {{ Incidence_Rate }}</li>
                <li>Taux de mortalité : {{ Case_Fatality_Ratio }}</li>
            </ul>
        </div>
    </div>

{% endblock %}

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}

{% block styles %}
     <script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.3/d3.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/topojson/1.6.9/topojson.min.js"></script>
    <script type="text/javascript" src="{% static 'home/js/datamaps.world.min.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

    {{ dicoPaysDeaths|json_script:"pays-deaths" }}
    {{ dicoException|json_script:"exception" }}
    {{ listeDate|json_script:"listeDate" }}
    {{ listeDeath|json_script:"listeDeath" }}
    {{ listeIR|json_script:"listeIR" }}

    <style>
        .active { fill: blue !important;}
        /*.datamaps-key dt, .datamaps-key dd {float: none !important;}
        .datamaps-key {right: -50px; top: 0;}*/
    </style>
{% endblock %}


{% block body %}
<div id="container">
    <div class="card-panel grey lighten-3" id="nav">
        <h4> Pays </h4>
        {% for pays in listePays %}
            <a href = "{% url 'home:pays' pays %}"> {{ pays }} </a>
            <br/>
        {% endfor %}
    </div>

    <div id="donnees">
        <div id="container2">

            <div class="card" id="map">
                <div class="card-content" id="cardMap">
                  <div id="containerMap" style="position:relative; width: 1000px; height: 600px;"></div>
                </div>
                <div class="card-tabs">
                  <ul class="tabs tabs-fixed-width" id="tabs">
                    <li class="tab"><a id="map1" class="active" href="tabs">Morts </a></li>
                    <li class="tab"><a id="map2" href="tabs">Cas actifs</a></li>
                    <li class="tab"><a id="map3" href="tabs">Taux d'incidence</a></li>
                    <li class="tab"><a id="map4" href="tabs">Taux de mortalité</a></li>
                  </ul>
                </div>
            </div>

            <div id="break"></div>

            <div class="card-panel teal lighten-3 white-text card small" id="statG">
                <h5> Données du {{ Date }}</h5>
                <ul>
                    <li>Nombre de déces : {{ Deaths }}</li>
                    <li>Nombre de cas confirmés : {{ Confirmed }}</li>
                    <li>Nombre de guérris : {{ Recovered }}</li>
                    <li>Nombre de cas actifs : {{ Active }}</li>
                    <li>Taux d'incidence : {{ Incidence_Rate }}</li>
                    <li>Taux de mortalité : {{ Case_Fatality_Ratio }}</li>
                </ul>
            </div>

            <div id="qqchose" class="card small">
                <canvas id="chartDeath"></canvas>
            </div>
            <div id="qqchose" class="card small">
                <canvas id="chartIR"></canvas>
            </div>
            <div id="qqchose">
            </div>


        </div>
    </div>

        <br/><br/>


</div>
{% endblock %}

home/templates/home/pays.html
{% extends 'home/base.html' %}

{% block body %}
    <nav>
        <div class="nav-wrapper blue-grey lighten-1">
            <div class="col s12">
                <a href="{% url 'home:index' %}" class="breadcrumb">Home</a>
                <a href="#" class="breadcrumb">{{ pays }}</a>
            </div>
        </div>
    </nav>


    <div id="container">
        <div class="card-panel grey lighten-3" id="nav">
            <h3> {{ pays }} </h3>
            {% for prov in listeProv %}
                <a href = "{% url 'home:province' pays prov %}"> {{ prov }} </a>
                <br/>
            {% endfor %}
        </div>

        <div id="body">
            <div id="container">
                <div class="card-panel teal lighten-3 white-text card small" id="stats">
                    <br/> <br/>
                    <h5> Données du {{ Date }}</h5>
                    <ul>
                        <li>Nombre de déces : {{ Deaths }}</li>
                        <li>Nombre de cas confirmés : {{ Confirmed }}</li>
                        <li>Nombre de guérris : {{ Recovered }}</li>
                        <li>Nombre de cas actifs : {{ Active }}</li>
                        <li>Taux d'incidence : {{ Incidence_Rate }}</li>
                        <li>Taux de mortalité : {{ Case_Fatality_Ratio }}</li>
                    </ul>
                </div>

                <div class="col s3" id="qqchose"></div>
            </div>
        </div>
    </div>
{% endblock %}

home/templates/home/province.html
{% extends 'home/base.html' %}

{% block body %}
    <nav>
        <div class="nav-wrapper blue-grey lighten-1">
            <div class="col s12">
                <a href="{% url 'home:index' %}" class="breadcrumb">Home</a>
                <a href="{% url 'home:pays' pays %}" class="breadcrumb">{{ pays }}</a>
                <a href="#" class="breadcrumb">{{ prov }}</a>
            </div>
        </div>
    </nav>


    <div id="container">
        <div class="card-panel grey lighten-3" id="nav">
            <h3> {{ prov }} </h3>
            {% for com in listeCom %}
                <a href = "{% url 'home:comte' pays prov com %}"> {{ com }} </a>
                <br/>
            {% endfor %}
        </div>

        <div id="body">
            <div id="container">
                <div class="col s3" id="stats">
                    <div class="card-panel teal lighten-3 white-text card small" id="stats">
                        <br/> <br/>
                        <h5> Données du {{ Date }}</h5>
                        <ul>
                            <li>Nombre de déces : {{ Deaths }}</li>
                            <li>Nombre de cas confirmés : {{ Confirmed }}</li>
                            <li>Nombre de guérris : {{ Recovered }}</li>
                            <li>Nombre de cas actifs : {{ Active }}</li>
                            <li>Taux d'incidence : {{ Incidence_Rate }}</li>
                            <li>Taux de mortalité : {{ Case_Fatality_Ratio }}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}